version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    # network_mode: host
    networks:
        - rabbitmq_go_net
  consumer:
    image: node:14.16.0-alpine3.10
    user: node
    working_dir: /home/node/app
    networks:
      - rabbitmq_go_net
    volumes:
      - .:/home/node/app
    command: npm run consumer 
  producer: 
    image: node:14.16.0-alpine3.10
    user: node
    working_dir: /home/node/app
    networks:
      - rabbitmq_go_net
    volumes:
      - .:/home/node/app
    command: npm run producer  

networks:
  rabbitmq_go_net:
    driver: bridge
